---
title: "Welcome to Eric Book"
description: |
  Welcome to our new blog, Eric Book. We hope you enjoy 
  reading what we have to say!
author:
  - name: Eric Book 
date: 2021-07-24
draft: false
base_url: https://ericbook.netlify.app
twitter:
  creator: "@erc_bk"
categories: [eda, R]
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

library(tidyverse, warn.conflicts = F)
```




Introductory words that summarizes what this profound post is going to explain to world.  

## Data  

This is data.  

```{r}
head(mtcars)
```


## Chart  

This is a chart.  

```{r echo=TRUE}
mtcars %>% 
  tibble::rownames_to_column("brand") %>% mutate(cyl = factor(cyl), cyl = fct_reorder(cyl, mpg)) %>% 
  ggplot(aes(x = mpg, y = cyl)) +
  geom_boxplot()
```

I am fucking starving. It looks like the cyl 4 has a median mpg of around 26 but the range is much wider than the other cylinder categories. Still plenty of variation between categories though.  





