---
title: "Projects"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(htmltools)
source("R/create-proj-card.R")
```


```{r}

create_proj_card(
  img_src = "images/projects/ind-covid-tracker.png",
  url = "https://ercbk.github.io/Indiana-COVID-19-Website/",
  title = "Indiana COVID-19 Tracker",
  text = "This website tracks metrics that include disease spread, hospital resources, social distancing, and age demographics",
  text2 = NULL
)

create_proj_card(
  img_src = "images/projects/ind-covid-data-final.png",
  url = "https://ercbk.github.io/indianacovid19data/",
  title = "{indianacovid19data}",
  text = "A R package for access to most of the processed and raw datasets from the Indiana COVID-19 Tracker project",
  text2 = NULL
)  

create_proj_card(
  img_src = "images/projects/nested-cv.png",
  url = "https://github.com/ercbk/nested-cross-validation-comparison",
  title = "Nested Cross-Validation Comparison",
  text = "Experimenting with various implementations and methods of nested cross-validation in R and Python",
  text2 = NULL
)

create_proj_card(
  img_src = "images/projects/health-equity.png",
  url = "https://github.com/ercbk/health-equity-lmdc",
  title = "Center for Health Equity",
  text = "Data products for Louisville Center for Health Equity - Louisville Metro Department of Corrections data",
  text2 = NULL
)

create_proj_card(
  img_src = "images/projects/ebtools.png",
  url = "https://ercbk.github.io/ebtools/",
  title = "{ebtools}",
  text = "A personal R package of miscellaneous data science functions",
  text2 = NULL
)

create_proj_card(
  img_src = "images/projects/reds-jaws.png",
  url = "https://github.com/ercbk/reds-jaws",
  title = "Reds JAWS",
  text = "A Shiny dashboard for evaluating Reds Hall of Fame candidates.",
  text2 = NULL
)


```

